# ~/.cargo/config.toml 
# or  ~/.cargo/config
# or  <PROJECT_ROOT>/.cargo/config.toml


#-- mirrors
[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[registries.ustc]
index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

#-- faster linker on linux
# install `clang` & `mold`
## reference: https://bevy.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional
[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
